### ISSUE TITLE
Support for multi-instance workloads

### ISSUE THREAD

**Issue by tomkerkhove** [PrometheusClientNet/Prometheus.Client#104]
This is more of a question but if I have a workload using 2 instances (A & B) - How can metrics reported by A be used in B?

Is this possible at all? For example, how do we sync state? Do we have to do it ourselves?

**Comment by sanych-sun** [comment]
It should be possible to add the same metric instance into more then 1 registry via ICollectorRegistry.Add. And then register several endpoints for each registry.

I can create a sample code for you tonight.

**Comment by sanych-sun** [comment]
Hi again!


            var registry1 = new CollectorRegistry();
            var factory = new MetricFactory(registry1);
            var counter = factory.CreateCounter("test_count", "helptext");

            var registry2 = new CollectorRegistry();
            registry1.TryGet("test_count", out var metric);
            registry2.Add(metric);

            IMetricServer metricServer = new MetricServer(registry1, new MetricServerOptions { Port = 9091 });
            metricServer.Start();

            IMetricServer metricServer2 = new MetricServer(registry2, new MetricServerOptions { Port = 9092 });
            metricServer2.Start();

            counter.Inc(5);

            Console.WriteLine("Press any key..");
            Console.ReadKey();
            metricServer.Stop();
            metricServer2.Stop();


It do the trick: client code works with single metric, but it reports to both endpoints.

**Comment by tomkerkhove** [comment]
Thanks for the sample but, unfortunately, my scenario is actually different I think.

I have one application which can run multiple instances. Every instance will have their own scrape endpoint which can be called and has a LB in front.

If instance A reports 10, how do we ensure instance B reports the same? Do we have to do that ourselves? Do we need to persist it?

**Comment by sanych-sun** [comment]
Oh I see. Is there k8s cluster to run your instances? If so, there is k8s operator to handle it.

Otherwise you have to install Prometheus server "inside" your application's network and scrap both servers. Or make some kind of proxy to each endpoint.

Anyway it will be better to let Prometheus have access to both servers, and calculate sum (or whatever you need) via Prometheus expressions while visualization.

**Comment by tomkerkhove** [comment]
It is running in Kubernetes indeed, but Prometheus only knows the Service it calls which will route to one of my instances. There is no way for Prometheus to be able to scrape both instances for this.

**Comment by phnx47** [comment]
Hello!

You should check your config, here documentation for kubernetes: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config 

When you can't scrape 2 services, maybe you can use Pushgateway.

**Comment by sanych-sun** [comment]
Here is some tutorial how to monitor application in k8s:

https://medium.com/kubernetes-tutorials/simple-management-of-prometheus-monitoring-pipeline-with-the-prometheus-operator-b445da0e0d1a

In general it means you have to install additional pod (operator) into your k8s cluster and add some labels to target services, so operator can query cluster to discover the services and automatically scrape them.

Or if there is no way to add something inside the cluster, then you probably have to use PushGateway, so each service will report its metrics on itself.

**Comment by sanych-sun** [comment]
@tomkerkhove as there is nothing to be done on Prometheus.Client side, I'll close the issue. Feel free to reopen it if there is anything else we can do to help.
