### ISSUE TITLE
Metric without labels is always tracked, even when not written

### ISSUE THREAD

**Issue by tomkerkhove** [PrometheusClientNet/Prometheus.Client#113]
After upgrading to 4.0 metrics always have an entry without labels and fixed `0`:
```
# HELP example Sample metric
# TYPE example gauge
example 0 0
example{instance="local",region="europe"} 100 1597840168812
```

Repro: https://github.com/tomkerkhove/Prometheus.Client.Repro

**Comment by sanych-sun** [comment]
The problem is in the following lines:
```

var metricFlags = MetricFlags.None;
metricFlags |= MetricFlags.IncludeTimestamp;
```

You have to start with MetricFlags.Default (**Default = SuppressEmptySamples**)

**Comment by tomkerkhove** [comment]
Problem is, I'm not reporting the metric without labels. It appears if I track the other one.

From my understanding the SupressEmpty refers to me reporting empty metrics, no?

**Comment by tomkerkhove** [comment]
On a related note, would be good to describe the flags of the enum with docs.

**Comment by sanych-sun** [comment]
For general use-cases it's better to report sample as soon as possible, event with empty value (for example if you have a counter and uses rate aggregate, to make first observations visible on visualization prometheus expects to have 0 as a first scrape). This is not a problem for labelled samples, as usually client code creates sample by calling WithLabels and make observation instantly. But user's code never explicitly creates sample without labels, so we introduce SuppressEmptySamples flag to ignore samples with empty value.

And yes, you are right we better add documentation on the flags.

**Comment by sanych-sun** [comment]
On other hand this option could be obsolete, as we uses Lazy<> internally to store the unlabelled sample and we can know if user's code access unlabelled sample.

@phnx47 What do you think are we safe to remove the SuppressEmptySamples flag and parameter? But it will be another breaking change =(

**Comment by phnx47** [comment]
```   [Flags]
    public enum MetricFlags
    {
        None = 0,

        SuppressEmptySamples = 1,

        IncludeTimestamp = 2,

        Default = SuppressEmptySamples
    }
```
`SuppressEmptySamples` already by default. Problem with combine SuppressEmptySamples and IncludeTimestamp. Need time for thihk...

**Comment by phnx47** [comment]
I understand more now. Yes, this is problem (((

I will hide 4.0.0, we will publish 4.0.1

**Comment by sanych-sun** [comment]
@tomkerkhove new package 4.1.0 was released to resolve the described problem.

Now you can simplify you code of metric creation

`var gauge = _metricFactory.CreateGauge("example", "Sample metric", true, new []{"instance","region"});`

**Comment by tomkerkhove** [comment]
Everything looks ok now, thanks for the (quick) fix!
