### ISSUE TITLE
Capability to parse generated Prometheus metrics

### ISSUE THREAD

**Issue by tomkerkhove** [PrometheusClientNet/Prometheus.Client#115]
Does the client provide capability to pull & parse generated metrics on an endpoint?

If not, do you recommend any other frameworks?

Use case would be to write integration tests to pull the generated metrics and ensure they are written correctly.

**Comment by sanych-sun** [comment]
We do not have such functionality. And I do not know such libraries.

But if you would like to export metrics in some another format (let's say json) it's possible. We have IMetricsWriter abstraction. If you implement your own metric writer you can export metrics to any format by using ICollectorRegistry.CollectToAsync method.

**Comment by tomkerkhove** [comment]
I'm mainly looking for parsing as if I would be a user but thanks for the tip anyway!
