### ISSUE TITLE
Off by one error, prevents logging metrics with 7 or more labels

### ISSUE THREAD

**Issue by Spinkelben** [PrometheusClientNet/Prometheus.Client#122]
https://github.com/PrometheusClientNet/Prometheus.Client/blob/3e5b9bf28bea2c0cbb18be6b90982ca6ef69dade/src/Prometheus.Client/LabelsHelper.cs#L142

It is in fact the 8th element that is the "Rest" element and not the 7th. `i` is counting the ordinal number and not the index.

Simplest code that exhibits the behaviour:

```c#
IMetricFactory fac = Prometheus.Client.Metrics.DefaultFactory;
var labels = new string[] { "label1", "label2", "label3", "label4", "label5", "label6", "label7", };
var counter = fac.CreateCounter("name", "help", false, labels);
```

**Comment by sanych-sun** [comment]
@Spinkelben thank you for contribution.

Wow nice catch! That algorithm works well for all tuples except from tuples that has 7, 14, etc components (because the code try to access Rest component, with is not there). We will fix the issue ASAP.

**Comment by Spinkelben** [comment]
Thank you for the quick turnaround! 👍
