### ISSUE TITLE
Prometheus.Client.Abstractions nuget package

### ISSUE THREAD

**Issue by tzographos** [PrometheusClientNet/Prometheus.Client#126]
Hello,

I can't seem to find a nuget package with the Abstractions of this client. Can you modify your CI in order to be able to build Prometheus.Client.Abstractions nuget packages ?

--Theodore

**Comment by sanych-sun** [comment]
We have not separated Abstractions into the package, but this definitely makes sense. I'll mark this issue as "enhancement" and we will include it into next release.

For now you have to reference the library itself.

Thank you for your contribution.
