### ISSUE TITLE
v4.3.0 is a breaking change

### ISSUE THREAD

**Issue by tomkerkhove** [PrometheusClientNet/Prometheus.Client#134]
Renovate wanted me to auto-upgrade to v4.3.0 but it's a breaking change: https://github.com/tomkerkhove/promitor/pull/1469

When checking the release notes (https://github.com/PrometheusClientNet/Prometheus.Client/releases/tag/v4.3.0) it is actually noted as a breaking one.

Just out of curiosity, was it on purpose to keep this on v4?

*PS: Feel free to setup GitHub Discussions so that I don't have to pollute your backlog :)*

**Comment by sanych-sun** [comment]
@tomkerkhove Sounds reasonable, we'd probably better to change major version. However it's easy to solve the breaking change, by just removing that using. I can do that for you =)

Sorry for inconveniences.

**Comment by sanych-sun** [comment]
I've create PR for Promitor to solve the issue. Fill free to merge it or modify in any way to meet your project standards.
The main motivation not to change version to 5 was that there is not so much "new" functionality to make the major release. :-)

Sorry again and we have Discussions board now.

I'll close the issue now, please reopen it if you need more assistance.

**Comment by tomkerkhove** [comment]
No problem and thanks for explaining and the PR!
