### ISSUE TITLE
Prometheus format changed in v2.0.0

### ISSUE THREAD

**Issue by tomkerkhove** [PrometheusClientNet/Prometheus.Client#15]
I'm working on upgrading to v2.0.0 but I'm having some concerns. 

When running my scenario the Prometheus scraping endpoint shows the following:
```
# HELP demo_queue_size Amount of active messages of the 'myqueue' queue # TYPE demo_queue_size gauge demo_queue_size 2895 
```

While in the past it showed the following:
```
# HELP demo_queue_size Amount of active messages of the 'myqueue' queue
# TYPE demo_queue_size Gauge
demo_queue_size 2316
```

This feels like a bug as this is not according to the Prometheus format. ([docs](https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md#text-format-example))

More details in [tomkerkhove/promitor #153](https://github.com/tomkerkhove/promitor/pull/153)

**Comment by tomkerkhove** [comment]
The only thing that I do is this: ([source]):
```csharp
app.UsePrometheusServer(prometheusOptions =>
{
    prometheusOptions.MapPath = scrapeEndpointPath;
    prometheusOptions.UseDefaultCollectors = false;
});
```

And writing via:
```csharp
var gauge = Metrics.CreateGauge(metricDefinition.Name, metricDefinition.Description);
gauge.Set(foundMetricValue);
```

**Comment by phnx47** [comment]
I checked Promitor code. Everything is fine.

![image](https://user-images.githubusercontent.com/1101691/45599961-aa4f7a80-b9fd-11e8-9a4b-ed7bd1bde03e.png)

**Comment by phnx47** [comment]
I need more information for debug or some unit tests

**Comment by tomkerkhove** [comment]
You'll need to check the branch of the PR. Master is fine currently.

I'd love to give you more info, but that's all I have..

**Comment by phnx47** [comment]
![image](https://user-images.githubusercontent.com/1101691/45600634-a543f880-ba08-11e8-8a40-7d219eb91299.png)

I can't reproduce this...

Maybe your browser wrong display '\n'?

**Comment by tomkerkhove** [comment]
That's exactly it - Edge is not showing it correctly and works fine in Chrome.
Sorry for this lame issue & your waste of time but thanks for having a look!

Closing issue.

**Comment by HenryKeen** [comment]
hi guys, I don't know if this is the same issue but I'm seeing this when using `Prometheus.Client.Owin` and its related to the contentType defaulting to `text/html` instead of `text/plain`.

I have a PR to fix https://github.com/PrometheusClientNet/Prometheus.Client.Owin/pull/6

**Comment by tomkerkhove** [comment]
A-ha, that explains a lot. Thanks!
