### ISSUE TITLE
Missing line feeds from the metrics endpoint

### ISSUE THREAD

**Issue by HenryKeen** [PrometheusClientNet/Prometheus.Client#16]
Hi

I'm having an issue since updating to 2.0 version of the package where the line endings have disappeared. It looks fine from the code so I'm wondering if this is an environment issue or if this is common?

The web project is a net461 project. I'm using the Prometheus.Client.Owin plugin.

This is what I'm seeing when hitting `/metrics` in chrome...

![screen shot 2018-09-19 at 14 51 49](https://user-images.githubusercontent.com/4572367/45757575-984b2300-bc1b-11e8-9c2b-b611c8143f05.png)

**Comment by phnx47** [comment]
It looks like #15. No bug with line. Is Prometheus correctly picks up data?

I tested it in net45. I will try with net461

**Comment by HenryKeen** [comment]
Managed to fix the issue with this PR https://github.com/PrometheusClientNet/Prometheus.Client.Owin/pull/6

**Comment by HenryKeen** [comment]
do you mind pulling? feels like a no-brainer as the ContentType header should be `text/plain` anyway

**Comment by phnx47** [comment]
Good, I didn't think it was necessary. But with Content Type will be definitely better.

@HenryKeen Thank you!
