### ISSUE TITLE
Support for timestamps in metrics

### ISSUE THREAD

**Issue by tomkerkhove** [PrometheusClientNet/Prometheus.Client#18]
Are there plans to provide support for timestamp in metrics?

This is officially supported by Prometheus: https://prometheus.io/docs/instrumenting/exposition_formats/
> metric_name [
  "{" label_name "=" `"` label_value `"` { "," label_name "=" `"` label_value `"` } [ "," ] "}"
] value [ timestamp ]

**Comment by phnx47** [comment]
I need time for research

**Comment by phnx47** [comment]
I will come back in next year. Sorry for waiting.

—
Сергей

________________________________

**Comment by phnx47** [comment]
In Progress...

**Comment by tomkerkhove** [comment]
> I will come back in next year. Sorry for waiting.

No problem, take your time and thank you!

**Comment by phnx47** [comment]
@tomkerkhove  Published to [MyGet](https://www.myget.org/feed/phnx47-beta/package/nuget/Prometheus.Client/2.1.0-build67) for test.

**Comment by tomkerkhove** [comment]
It looks fine for me but do you also have plans to allow us to specify the stamp to use?

I'm not sure if the tracked value is correct, however, because in my sample it has `1548140899` which turns out to be 1/22/2019, 10:08:19 AM which is the local time and not GMT.

**Comment by tomkerkhove** [comment]
Thanks! Will create a seperate issue for passing timestamp when this one is closed

**Comment by tomkerkhove** [comment]
Any reasons why you are not using `DateTimeOffset.UnixEpoch` rather than calculating it yourself?

**Comment by phnx47** [comment]
DateTimeOffset.UnixEpoch isn't exists in netstandard

**Comment by phnx47** [comment]
Published 2.1.0

**Comment by tomkerkhove** [comment]
Closing as this works and is pushed. Thanks!
