### ISSUE TITLE
Introduce IMetricsWriter

### ISSUE THREAD

**Issue by sanych-sun** [PrometheusClientNet/Prometheus.Client#23]
Review scrapping process to use IMetricsWriter instead of generating CMetric object. This should reduce memory allocation while scrapping.

**Comment by phnx47** [comment]
Incorrect format in Example.

https://github.com/PrometheusClientNet/Prometheus.Client.Examples/tree/master/WithoutExtensions/CoreWebWithoutExtensions_2.1

![image](https://user-images.githubusercontent.com/1101691/53132771-c98c9e00-3581-11e9-8409-9b43d4783465.png)

**Comment by phnx47** [comment]
@sanych-sun 

- Remove '\n'
- HELP and TYPE, before metric_name
- Check last line, it is seems like closed stream

**Comment by sanych-sun** [comment]
Wow, help and type in wrong position... I must sleep more :).

I'll fix this ASAP and create unit tests for the metric writer.

Thanks
Alex
