### ISSUE TITLE
ThreadSafeLong-based counter

### ISSUE THREAD

**Issue by sanych-sun** [PrometheusClientNet/Prometheus.Client#24]
Most of the counters are naturally int-based (number of events), however current version of the library uses double as internal representation of the counter to follow the Prometheus conventions. This approach require some extra effort in .Net implementation.

It might make sense to add new type of counter based on long, so we can take advantages of build-in atomic operations. 

Let's discuss the suggestion.

**Comment by phnx47** [comment]
Yes. We can use 'long' for public.
