### ISSUE TITLE
Add benchmarks collection

### ISSUE THREAD

**Issue by sanych-sun** [PrometheusClientNet/Prometheus.Client#29]
Introduce benchmarks collection for critical parts of library's functionality:
1) Metrics creation/retrieving via the Factory
2) Value observations (method like Counter.Inc)
3) Metrics collection

Probably based on [BenchmarkDotNet library](https://github.com/dotnet/BenchmarkDotNet).

In ideal situation - benchmarks should be collected as a part of CI pipeline and published so we can see changes from version to version.

**Comment by sanych-sun** [comment]
I can add implement benchmarks, however I need help to integrate them somehow in build process.

**Comment by phnx47** [comment]
@sanych-sun I can integrate it in appveyor or travis
