### ISSUE TITLE
Add code analyzers

### ISSUE THREAD

**Issue by sanych-sun** [PrometheusClientNet/Prometheus.Client#30]
I suggest to add at least following analyzers:
1) [SonarAnalyzer.CSharp](https://www.nuget.org/packages/SonarAnalyzer.CSharp/) - provide number of analyzers to enforce using of C# best practices
2) [StyleCop.Analyzers](https://www.nuget.org/packages/StyleCop.Analyzers/) - enforce single code style

Both can be referenced as a package reference so no extra effort needed to configure CI. List of rules and configuration should be adjusted as much as possible to the current code style.

**Comment by phnx47** [comment]
I used Codacy before... Now not use anything. I need time for research

**Comment by sanych-sun** [comment]
I can make an example in separate branch, so you can play with it before move it into master.

**Comment by sanych-sun** [comment]
I've created branch with included analyzers mentioned above, so you can play with the analyzers. Now there are approx 500 warnings (most of them are trivial, like "Documentation text should end with a period" or "A property should not follow a method") I'll fix all of them if e decide to use this analyzers.

BTW, Sonar found useless variable mentioned by you from the previous pull request:
![image](https://user-images.githubusercontent.com/31327136/53283517-74c16280-36fc-11e9-8fd0-353ed4ae13d4.png)

**Comment by phnx47** [comment]
It is conflict with Rider analyzer. I prefer use only one.

For code style, better use .editorconfig: https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017

**Comment by sanych-sun** [comment]
Ok, no problem. I'll close the issue

**Comment by phnx47** [comment]
@sanych-sun I read more about StyleCop. I think, we can use it in future, I need time to set up rules

**Comment by sanych-sun** [comment]
Ups. I've already delete the branch from origin. I'll restore it tonight.

Take you time for investigation, but it would be really great to include this into v3 release. Let me know if you need any help with some rules/configuration.

**Comment by phnx47** [comment]
I restored branch.

I fix all conflict with my Rider rules: https://www.jetbrains.com/help/rider/StyleCop_Styles.html?Wave=183

**Comment by phnx47** [comment]
Added codefactor: https://www.codefactor.io/repository/github/prometheusclientnet/prometheus.client

Working with style guide .editorconfig + stylecop in branch

**Comment by sanych-sun** [comment]
Looks nice!

Only 1 question: are you going to have a package reference to the analyzer?
I'm asking because I prefer to see code analysis result instantly, not
after my code pushed to original or even merged into master.

Thanks

**Comment by phnx47** [comment]
Codefactor: Just check result, I used Cadacy before. Everyone can see that

For develop: 
 - Rider: use .editorconfig and stylecop configs
 - Visual Studio: I don't use Windows, I think need install StyleCop.Analyzers

**Comment by phnx47** [comment]
We have EditorConfig + StyleCop. It is works in Visual Studio and Rider/Resharper.

We have *.DotSettings for  Rider/Resharper.

We have CodeFactor for PR analyze.

**Comment by phnx47** [comment]
@sanych-sun I think, we can close issue.
