### ISSUE TITLE
Metric's state access inconsistency

### ISSUE THREAD

**Issue by sanych-sun** [PrometheusClientNet/Prometheus.Client#41]
I've noticed that we have inconsistency in access to metric's state:
- for Counter and Gauge library provides observation methods (Inc and Dec) and publicly available readonly property Value, which uncovers counter and gauge recorded state
- however for Histogram and Summary there is observation methods only, there is no way to get current state.

I'm not sure if there are any use-case  which requires access to the metric's state from the code. But it would be nice to remove this inconsistency, probably by implementing publicly available methods to get current state for Summary and Histogram. 

Need someone's opinion on that.

**Comment by phnx47** [comment]
@sanych-sun Thank you! I will think about it

**Comment by phnx47** [comment]
@djluck Hello! If you have time, we would appreciate your opinion.

**Comment by phnx47** [comment]
@sanych-sun We should make public GetAllLabels too

**Comment by sanych-sun** [comment]
OK, I'll return it v3 scope

**Comment by sanych-sun** [comment]
There is definitely some use cases require access to state of metric. Here is similar [issue reported to official library](https://github.com/prometheus-net/prometheus-net/issues/139)

BTW: changes are done, can close the issue, unless someone want to add any details. #
