### ISSUE TITLE
Stong Named Assemblies

### ISSUE THREAD

**Issue by ScottGuymer** [PrometheusClientNet/Prometheus.Client#55]
I am investigating the use of Prometheus and have a requirement for strong names in all dependencies.

Is there any objection to adding strong naming to this project? And other parts of the ecosystem such as Prometheus.Client.MetricServer.

**Comment by phnx47** [comment]
@ScottGuymer No problem. I will research this, and you can make PR.

**Comment by ScottGuymer** [comment]
Happy to contribute!

**Comment by ScottGuymer** [comment]
Microsoft advice is to check in the keys for OSS projects.
https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies

Althought advice seems to vary
https://stackoverflow.com/a/396159
https://stackoverflow.com/a/886024

I will work up a PR with signing activated and a key checked into the repo

**Comment by phnx47** [comment]
Merged!

**Comment by ScottGuymer** [comment]
@phnx47 to be able to string name the dependent assemblies (eg Prometheus.Client.MetricsServer) this will need to be published on NuGet as the dependent assemblies pull this from NuGet

**Comment by phnx47** [comment]
@ScottGuymer Ok, I will publish later

**Comment by ScottGuymer** [comment]
Great i can then work on getting the rest of the projects upgraded.

**Comment by phnx47** [comment]
3.0.0-rc2

**Comment by phnx47** [comment]
Now all extensions: 'Strong Named Assemblies'
