### ISSUE TITLE
Prometheus 3.0 returns corrupted output

### ISSUE THREAD

**Issue by vilmysj** [PrometheusClientNet/Prometheus.Client#66]
Hi, 

we are using Prometheus.Client with Prometheus.Client.Owin, after update to 3.0 version `/metrics` endpoint returns corrupted result:
```
http_server_request_duration_seconds_bucket{method="GET",controller="test",action="testaction",code="200",error="False",le="0.001"} 0
="0.25"} 27525
http_server_request_duration_seconds_bucket{method="GET",controller="test",action="testaction",code="200",error="False",le="0.01"} 790
```
or
```
http_server_request_duration_seconds_sum{method="GET",controller="test",action="testaction2",code="200",error="False"} 120.9984338
http_server_request_duration_seconds_count{method="GET",controller="test",action="testaction2",code="200",error="False"} 18464_sum{method="GET",controller="test2",action="getbyid",code="200",error="False"} 25.6608671000001
http_server_request_duration_seconds_count{method="GET",controller="test2",action="getbyid",code="200",error="False"} 10655
```

Here is simple application which can reproduce this issue:
https://github.com/vilmysj/PrometheusClientTest

It creates multiple metrics and then calls `/metrics` endpoint with 2 concurrent calls. Prometheus.Client writes corrupted output after 2-5 iterations. Results are stored in files.

Same application with Prometheus.Client 2.2.2 always returns correct output
https://github.com/vilmysj/PrometheusClientTest/tree/prometheus-2.2.2

**Comment by sanych-sun** [comment]
@vilmysj  thank you for the report, I'll take a look at the issue ASAP.

**Comment by sanych-sun** [comment]
Fast update: I tried to reproduce the issue via MetricServer instead of Owin - and there are no problems. So issue not in the Core lib, but in Owin integration. I'll keep you updated on my findings.

**Comment by vilmysj** [comment]
I tried to use Prometheus.Client.AspNetCore and still getting corrupted results
https://github.com/vilmysj/PrometheusClientTest/tree/netcoreapp2.2

**Comment by sanych-sun** [comment]
@vilmysj I found the root cause of the issue. As it turned out - it's in core library (we use ArrayPool to reduce memory allocation and sometimes MetricWriter returns the same array into pool twice... however in multi-thread environment it could be already in use by another instance).

I'll create pull request to fix the issue tonight.

Thank you again for the reported issue with very useful test frame!!!

**Comment by sanych-sun** [comment]
@vilmysj Pull request to fix the problem was created. Let's wait for review and new release, then all integration libraries have to be updated.

**Comment by vilmysj** [comment]
Thank you for quick fix

**Comment by phnx47** [comment]
@vilmysj  @sanych-sun  Check it in MyGet, before release, please

**Comment by sanych-sun** [comment]
@phnx47  I've just checked. It works now.

**Comment by phnx47** [comment]
Released!
