### ISSUE TITLE
Remove StyleCop.Analyzers from project dependencies

### ISSUE THREAD

**Issue by sanych-sun** [PrometheusClientNet/Prometheus.Client#71]
There is reference to Remove StyleCop.Analyzers for netstandard1.3 target in Prometheus.Client.csproj. It's unnecessary and should be removed.

**Comment by phnx47** [comment]
I don't see problem

![image](https://user-images.githubusercontent.com/1101691/62664223-6d78d300-b983-11e9-9a22-dc90a3846fa7.png)

**Comment by sanych-sun** [comment]
Yep, but in csproj file we have the following line:

`<PackageReference Update="StyleCop.Analyzers" Version="1.1.1-rc.114" />`

It looks useless.
