### ISSUE TITLE
Broken double value representation under .Net Core

### ISSUE THREAD

**Issue by Sergey-Terekhin** [PrometheusClientNet/Prometheus.Client#75]
Hello!
We use prometheus client under .Net Core with the default culture where decimal separator is comma (','). And we get broken text representation of metrics (instead of dots, commas are used):
```
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 4,28125
```
Such representation can not be parsed by Prometheus Server.

It seems to be issue here:  `Prometheus.Client/src/Prometheus.Client/MetricsWriter/MetricsTextWriter.cs, line 264` (method **`Write(double value)`**).

I assume that instead of `value.TryFormat(buff, out var charsize);` it should be **`value.TryFormat(buff, out var charsize, CultureInfo.InvariantCulture);`** like in the code branch below: `Write(value.ToString(CultureInfo.InvariantCulture));`

**Comment by sanych-sun** [comment]
Thank you for reporting this. We will fix it ASAP and include into next release.

**Comment by sanych-sun** [comment]
The issue has been fixed and will be included into 3.0.2 release.

@Sergey-Terekhin It would be nice if you help us with testing the development build on MyGit.

Thanks

**Comment by Sergey-Terekhin** [comment]
Checked build on MyGet - seems to be fixed 👍 
Thank you!

**Comment by sanych-sun** [comment]
@Sergey-Terekhin  Thank you for confirming the fix. We will create hot-fix package soon.

**Comment by sanych-sun** [comment]
@Sergey-Terekhin just want to let you know that package has been created and available on nuget.

**Comment by Sergey-Terekhin** [comment]
Thanks, already updated package in my service :)
