### ISSUE TITLE
 Prometheus Pushgateway

### ISSUE THREAD

**Issue by anisimovyuriy** [PrometheusClientNet/Prometheus.Client#8]
Thanks for the gr8 .net client! I wonder if there is a plan to support "Push Gateway"?

**Comment by phnx47** [comment]
Yes. I will release "Push Gateway" on next week

**Comment by anisimovyuriy** [comment]
@phnx47 - I know that you might be working on it but if not I'm glad to contribute. Could you check my [PR](https://github.com/PrometheusClientNet/Prometheus.Client/pull/10):

Thanks!

**Comment by phnx47** [comment]
Oh, thank you.

But, I want to use this repositroy: https://github.com/PrometheusClientNet/Prometheus.Client.MetricPusher

I'll check code and create nuget

**Comment by anisimovyuriy** [comment]
sure thing, thanks @phnx47!

**Comment by john199604** [comment]
@phnx47 can you please add some docs on how to use this https://github.com/PrometheusClientNet/Prometheus.Client.MetricPusher ?

**Comment by phnx47** [comment]
I'm not finished yet. Need some tests

**Comment by anisimovyuriy** [comment]
I can help you with docs @phnx47 - at least my part

**Comment by phnx47** [comment]
@anisimovyuriy I will be grateful to you

**Comment by phnx47** [comment]
I need more time for think about Pushgateway feature and code

**Comment by anisimovyuriy** [comment]
@phnx47 - please check my latest PR. if you were able to publish new nuget package with PushMetricService - I'd  add to Prometheus.Client.AspNetCore - PushHostedService (Background worker with timer implementation to push metrics) and Aspnetcore project with actual example.

**Comment by phnx47** [comment]
@anisimovyuriy ok, thank you. I will check. But I would like to keep this code in a separate library.  I think, we need less dependencies in the base library. Background worker too, I think that he should be in https://github.com/PrometheusClientNet/Prometheus.Client.MetricPusher

**Comment by anisimovyuriy** [comment]
@phnx47 - good point - I'll send you PR to MetricPusher soon.

**Comment by phnx47** [comment]
@anisimovyuriy What do you think about my implementation? https://github.com/PrometheusClientNet/Prometheus.Client.MetricPusher/tree/dev

**Comment by phnx47** [comment]
Also, we can try add timer-based worker as alternative in code.

**Comment by phnx47** [comment]
Published

https://www.nuget.org/packages/Prometheus.Client.MetricPusher
