### ISSUE TITLE
Clarification on goals/pros/cons/differences to prometheus-net

### ISSUE THREAD

**Issue by dm3** [PrometheusClientNet/Prometheus.Client#9]
Hello,

I couldn't find any information on how this project is different to [prometheus-net](https://github.com/prometheus-net/prometheus-net) except for the brief mention that it's a fork. 

Would be great if you could elaborate the goals/pros/cons/differences of this project compared to "prometheus-net" in the README. Given there's not much info there currently, the alternative is to read the code and/or try both APIs. 

I expect most users would simply compare the projects based on the number of Github stars/Nuget downloads/Commit activity and choose in favour of the original "prometheus-net". The clarification would help promote the project!

**Comment by phnx47** [comment]
I wrote some information in Readme.

I created a fork for my own projects. Now I think about its development. Write more issues.
