### ISSUE TITLE
Add support for initializing histogram metrics with labels to zero

### ISSUE THREAD

**Issue by jnovick** [PrometheusClientNet/Prometheus.Client#90]
I need the ability to use the increase or rate function and see when a metric goes from uninitialized (Which I consider 0) to a non-zero value. According to [official docs](https://prometheus.io/docs/instrumenting/writing_clientlibs/), 

> There SHOULD be a way to initialize a given Child with the default value, usually just calling labels(). Metrics without labels MUST always be initialized to avoid [problems with missing metrics](https://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics).

This means, I should be able to specify in advance a metric's labels to set to zero so initial scraping shows that zero value.

There is already a workaround for `Counter` and `Gauge` by calling `metrics.WithLabels("exampleLabel").Inc(0)` substituting in the appropriate labels. There is not a workaround for `Histogram` that I can find though. This is of course not possible when possible labels are not know in advance, but when they are known in advance, it is very beneficial to be able to specify them.

Similar issue in another Prometheus Library: https://github.com/siimon/prom-client/issues/118

**Comment by sanych-sun** [comment]
@jnovick I believe there is functionality to handle your use-case. 

If you use MetricFactory to create a metrics there is an option to suppressEmptySamples (which is true by default), try to set it to false while creating the metric. I cannot test the suggestion yet, but I can create a sample for you later.

**Comment by jnovick** [comment]
Thanks you. If I set that to false then simply calling `WithLabels` initializes the values to zero and accomplishes what I want.
